{
  MessagingException e=flowRunner(flowName).runExpectingException();
  Throwable cause=ExceptionUtils.getRootCause(e);
  assertThat(CUSTOM_EXCEPTION,is(sameInstance(cause)));
}
