{
  NamingException e=(NamingException)t;
  return e.getRootCause();
}
