{
  try {
    failingStatement.call().validateConstruct();
    fail("should have got a FlowConstructInvalidException");
  }
 catch (  final Exception e) {
    assertTrue(e instanceof FlowConstructInvalidException);
  }
}
