{
  expectedException.expectCause(instanceOf(InitialisationException.class));
}
