{
  ConnectException causeCauseException=new ConnectException();
  IOException causeException=new IOException(causeCauseException);
  MessagingException exception=new MessagingException(CoreMessages.createStaticMessage(""),mockEvent,causeException);
  assertThat(exception.causedExactlyBy(ConnectException.class),is(true));
  assertThat(exception.causedExactlyBy(SocketException.class),is(false));
  assertThat(exception.causedExactlyBy(IOException.class),is(false));
  assertThat(exception.causedExactlyBy(MessagingException.class),is(false));
}
