{
  Exception e=new RuntimeException();
  doThrow(e).when(((Initialisable)source)).initialise();
  expectedException.expectCause(is(sameInstance(e)));
  messageSource.initialise();
}
