{
  Constructor ctor=exceptionClass.getConstructor(new Class[]{String.class,Throwable.class});
  Throwable exception=(Throwable)ctor.newInstance(new Object[]{"Something Failed",new IOException("Nested, something failed")});
  assertNotNull(exception.getCause());
  assertTrue(exception.getCause() instanceof IOException);
  assertNotNull(exception.getMessage());
  ctor=exceptionClass.getConstructor(new Class[]{String.class});
  exception=(Throwable)ctor.newInstance(new Object[]{"Something Failed"});
  assertNull(exception.getCause());
  assertNotNull(exception.getMessage());
}
