{
  try {
    return this.next.execute(processingCallback,executionContext);
  }
 catch (  MessagingException e) {
    if (e.handled()) {
      return e.getEvent();
    }
    throw e;
  }
}
