{
  fail("Should throw an exception");
}
