{
  for (  ExceptionNotification exceptionNotification : exceptionNotifications) {
    Throwable exceptionThrownCause=exceptionNotification.getException().getCause();
    if (exceptionThrownCause != null && expectedExceptionCauseType.isAssignableFrom(exceptionThrownCause.getClass())) {
      return this;
    }
  }
  throw new AssertionError(format("Exception exception caused by type %s was not thrown",expectedExceptionCauseType.getName()));
}
