{
  MessagingException e=flowRunner("validate").runExpectingException();
  Throwable cause=ExceptionUtils.getRootCause(e);
  assertThat(cause,is(instanceOf(ValidationException.class)));
}
