{
  IOException causeException=new IOException("");
  MessagingException exception=new MessagingException(CoreMessages.createStaticMessage(""),mockEvent,causeException);
  assertThat(exception.causedBy(IOException.class),is(true));
  assertThat(exception.causedBy(MessagingException.class),is(false));
  assertThat(exception.causedBy(Exception.class),is(true));
}
