{
  try {
    startLatch.await();
  }
 catch (  InterruptedException e) {
    logger.warn("Retry thread interrupted for callback: " + callback.getWorkDescription());
    return;
  }
  try {
    context.setDelegateContext(delegate.execute(callback,workManager));
  }
 catch (  Exception e) {
    this.exception=e;
    logger.error("Error retrying work",e);
  }
}
