{
  java.lang.Error error=new java.lang.Error();
  when(mockMessageProcessor.process(mockMuleEvent)).thenThrow(error);
  try {
    cut.execute(mockMessageProcessor,mockMuleEvent);
    fail("Exception should be thrown");
  }
 catch (  MessagingException e) {
    assertThat((java.lang.Error)e.getCause(),is(error));
  }
}
