{
  try {
    flowRunner("rollbackRollbackExceptionStrategy").withPayload(TEST_MESSAGE).nonBlocking().run();
    fail("Exception Expected");
  }
 catch (  ComponentException componentException) {
    assertThat(componentException.getCause(),instanceOf(FunctionalTestException.class));
  }
 finally {
    verify("rollbackRollbackExceptionStrategy");
    verify("rollbackExceptionStrategyChild");
  }
}
