{
  return exception(format("Error during login to %s@%s",user,host),e);
}
