{
  try {
    evaluate(expression,event);
    fail("ExpressionRuntimeException expected");
  }
 catch (  ExpressionRuntimeException e) {
    assertEquals(PropertyAccessException.class,ExceptionUtils.getRootCause(e).getClass());
  }
}
